import React,{useEffect,useRef,useState} from 'react';
import type {Context} from '@deepseek-ai/cordis';
import type {PropsRuntime} from '@deepseek-ai/dsh-client-ui-slots';
import type {} from '@deepseek-ai/dsh-client-ui-sidebar-right/client';
import type {} from '@deepseek-ai/dsh-client-resources/client';
import type {} from '@deepseek-ai/dsh-client-ui-renderer/client';
import {RemoteError} from '@deepseek-ai/dsh-typert-protocol';
import {WritingEditor} from './Editor.js';
import {css,displayValue,documentId,evidenceCards,exportReady,newId,resourceAddress,rows,selectedImpactIds,statusLabel,type Document,type Node,type Row,type Rpc} from './model.js';
declare module '@deepseek-ai/dsh-client-resources/client'{interface ResourceProtocolMap{'chuanshen-writing':{documentId:string;version:string}}}
declare module '@deepseek-ai/dsh-client-ui-sidebar-right/client'{interface SidebarRightTabParamsMap{'workdsh-plate':{documentId?:string}}}
export const name='workdsh-plate-client';
export const inject=['slots','resources','sidebarRightTabs'];
type Draft={documentId:string;baseVersionId:string;content:Node[]};
type PageCallbacks={rpc:Rpc;download:(id:string,signal:AbortSignal)=>Promise<void>;getDraft:(tabId:string)=>Draft|undefined;setDraft:(tabId:string,draft:Draft|undefined)=>void};
export function apply(ctx:Context){
 const lifetime=new AbortController();ctx.effect(()=>()=>lifetime.abort());
 const drafts=new Map<string,Draft>();ctx.effect(()=>()=>drafts.clear());
 const getDraft=(id:string)=>drafts.get(id);
 const setDraft=(id:string,draft:Draft|undefined)=>{if(draft)drafts.set(id,structuredClone(draft));else drafts.delete(id);};
 const rpc:Rpc=async(endpoint,payload={},signal)=>{const response=await fetch('/api/workdsh-chuanshen',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint,payload}),signal:AbortSignal.any([lifetime.signal,...(signal?[signal]:[]),AbortSignal.timeout(120000)])});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.error?.message??'请求失败，内容已保留');return body.value;};
 const download=async(jobId:string,signal:AbortSignal)=>{const response=await fetch('/api/workdsh-chuanshen',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:'writing-download',payload:{job_id:jobId}}),signal:AbortSignal.any([lifetime.signal,signal,AbortSignal.timeout(120000)])});if(!response.ok||response.headers.get('content-type')?.includes('application/json')){const body=await response.json().catch(()=>({}));throw new Error(body.error?.message??'导出文件暂时无法下载');}const disposition=response.headers.get('content-disposition')??'';let filename=disposition.match(/filename="([^"\r\n]+)"/i)?.[1]??'文稿';const encoded=disposition.match(/filename\*=UTF-8''([^;\r\n]+)/i)?.[1];if(encoded){try{filename=decodeURIComponent(encoded);}catch{}}filename=filename.replace(/[\\/\x00-\x1f]/g,'_');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);};
 ctx.effect(()=>ctx.resources.register<'chuanshen-writing'>({protocol:'chuanshen-writing',async *open(address,{signal}){const id=documentId(address);if(!id){yield {ok:false,error:new RemoteError('gateway/bad-request','文稿地址无效',{})};return;}try{const doc=await rpc<Document>('writing-document',{document_id:id},signal);yield {ok:true,value:{documentId:doc.id,version:doc.current_version_id}};}catch{if(!signal.aborted)yield {ok:false,error:new RemoteError('gateway/internal','文稿暂时不可用',{})};}}}));
 ctx.effect(()=>ctx.sidebarRightTabs.register({id:'workdsh-plate',kind:'workdsh-plate',patterns:['dsh-resource://chuanshen-writing/**'],title:()=> 'Plate · 写作',guide:[{id:'workdsh-plate',order:46,title:()=> 'Plate 写作',description:()=> '编辑有依据的文稿与预览数据变化'}]}));
 ctx.effect(()=>ctx.slots.inject('sidebar.right.pane.tab',()=>ctx.slots.register({name:'sidebar.right.pane.tab',key:'workdsh-plate',inject:()=>({rpc,download,getDraft,setDraft})},Page)));
}
function Page(props:PropsRuntime<'sidebar.right.pane.tab'>&PageCallbacks){
 const tab=props.useTabInfo().tab;const params=tab.navigation.params as {documentId?:string}|undefined;
 const [id,setId]=useState<string|undefined>(documentId(tab.contentId??'')??params?.documentId);
 const [projects,setProjects]=useState<Row[]>([]),[project,setProject]=useState(''),[documents,setDocuments]=useState<Row[]>([]);
 const [doc,setDoc]=useState<Document|null>(null),[content,setContent]=useState<Node[]>([]),[facts,setFacts]=useState<Row[]>([]),[evidence,setEvidence]=useState<Row[]>([]);
 const [pane,setPane]=useState('正文'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[draftBase,setDraftBase]=useState(''),[editorRevision,setEditorRevision]=useState(0);
 const [factKey,setFactKey]=useState(''),[value,setValue]=useState(''),[reason,setReason]=useState(''),[changing,setChanging]=useState(false);
 const [preview,setPreview]=useState<Row|null>(null),[chosen,setChosen]=useState<string[]>([]),[applied,setApplied]=useState<string>(),[history,setHistory]=useState<Row[]>([]),[exports,setExports]=useState<Row[]>([]);
 const lock=useRef(false);const call=props.rpc;
 const run=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{lock.current=false;setBusy(false);}};
 const load=async(nextId=id)=>{if(!nextId)return;const d=await call<Document>('writing-document',{document_id:nextId},tab.signal);const draft=props.getDraft(tab.id);const local=draft?.documentId===d.id?draft:undefined;setDoc(d);setContent(local?.content??d.current_version?.content??[]);setDraftBase(local?.baseVersionId??d.current_version_id);setDirty(!!local);setEditorRevision(n=>n+1);if(local&&local.baseVersionId!==d.current_version_id)setError('服务端已有新版本，本地未保存稿已保留；请合并后重试，或放弃本地修改');const [f,e]=await Promise.all([call('writing-facts',{project_id:d.project_id},tab.signal),call('writing-evidence',{document_id:d.id},tab.signal)]);setFacts(rows(f));setEvidence(rows(e));};
 useEffect(()=>{void run(async()=>{setProjects(rows(await call('writing-projects',{},tab.signal)));if(id)await load(id);});},[id]);
 useEffect(()=>{if(project)void run(async()=>setDocuments(rows(await call('writing-documents',{project_id:project},tab.signal))));},[project]);
 useEffect(()=>{const target=documentId(tab.contentId??'')??params?.documentId;if(target&&target!==id&&!dirty)setId(target);},[tab.navigation.revision]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const proposals=rows(preview?.impact?.content_proposals);
 const payload=()=>({document_id:doc!.id,project_id:doc!.project_id});
 const save=()=>run(async()=>{if(!doc)return;await call('writing-save',{...payload(),content,base_version_id:draftBase||doc.current_version_id,request_id:newId()},tab.signal);props.setDraft(tab.id,undefined);await load();});
 const change=(key:string)=>{const fact=facts.find(f=>f.fact_key===key);if(!fact){setError('未找到此数值的当前输入，请刷新后查看依据');return;}if(['deterministic_computation','semantica_inference'].includes(fact.fact_type)){setPane('指标');setError('这是计算或推演结果，请调整其原始输入');return;}if(doc?.current_version?.status==='published'){setError('已定稿文稿不可直接修改，请先创建新草稿');return;}setFactKey(key);setValue('');setReason('');setChanging(true);};
 const previewChange=()=>run(async()=>{if(!value.trim()||!Number.isFinite(Number(value)))throw new Error('请输入有效数值');const p=await call<Row>('writing-preview',{...payload(),fact_key:factKey,new_value:Number(value),reason},tab.signal);setPreview(p);setChosen(rows(p.impact?.content_proposals).filter(x=>x.selectable).map(x=>x.block_id));setChanging(false);});
 const cancel=()=>run(async()=>{if(preview)await call('writing-cancel',{...payload(),preview_id:preview.id},tab.signal);setPreview(null);});
 const apply=()=>run(async()=>{const selectedIds=selectedImpactIds(proposals,chosen);if(!preview||!selectedIds.length)return;await call('writing-apply',{...payload(),preview_id:preview.id,accepted_block_ids:selectedIds},tab.signal);setApplied(preview.id);setPreview(null);await load();});
 return <section className="wd-plate" style={{position:'relative'}} data-testid="plate-writing"><style>{css}</style><header><strong>{doc?.title??'Plate 写作'}</strong>{doc&&<><span>V{doc.current_version?.version}</span><button disabled={busy||!dirty} onClick={()=>void save()}>保存</button><button disabled={busy||dirty} onClick={()=>void run(()=>load())}>刷新</button>{dirty&&<button disabled={busy} onClick={()=>{if(window.confirm('放弃当前未保存修改？服务器版本不会删除。'))void run(async()=>{props.setDraft(tab.id,undefined);await load();});}}>放弃未保存修改</button>}</>}</header>
 {!doc?<div className="picker"><label>写作项目 <select aria-label="写作项目" value={project} onChange={e=>setProject(e.target.value)}><option value="">请选择</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name??p.title}</option>)}</select></label>{documents.map(d=><button key={d.id} onClick={()=>{setId(d.id);tab.actions.openResource(resourceAddress(d.id));}}>{d.title}</button>)}</div>:<><nav>{['正文','依据','指标','版本','导出'].map(p=><button key={p} disabled={busy} aria-pressed={pane===p} onClick={()=>{setPane(p);if(p==='版本')void run(async()=>setHistory(rows(await call('writing-versions',payload(),tab.signal))));if(p==='导出')void run(async()=>setExports(rows(await call('writing-exports',payload(),tab.signal))));}}>{p}</button>)}{applied&&<button disabled={busy||dirty} onClick={()=>void run(async()=>{await call('writing-rollback',{...payload(),preview_id:applied},tab.signal);setApplied(undefined);await load();})}>撤销上次联动</button>}</nav>
 {pane==='正文'&&<WritingEditor key={`${doc.current_version_id}:${draftBase}:${editorRevision}`} content={content} readOnly={busy||!!preview||doc.current_version?.status==='published'} onChange={v=>{const changed=JSON.stringify(v)!==JSON.stringify(doc.current_version?.content??[]);setContent(v);setDirty(changed);props.setDraft(tab.id,changed?{documentId:doc.id,baseVersionId:draftBase||doc.current_version_id,content:v}:undefined);}} onSelect={setSelected} onFact={change}/>}
 {pane==='依据'&&<div className="details">{selected&&<button onClick={()=>setSelected('')}>查看全文依据</button>}{evidence.filter(x=>!selected||x.block_id===selected||x.chunk_id===selected).map((e,i)=><article key={e.block_id??i}><strong>{e.section??e.section_title??'段落依据'}</strong><small> · {statusLabel(e.status)}</small><p>{e.text}</p>{evidenceCards(e).map((source,index)=><section className="source-card" key={index}><strong>{source.title}</strong><div className="source-meta">{source.kind} · {source.version} · {source.verification} · {source.freshness}</div>{source.location&&<div className="source-meta">{source.location}</div>}<blockquote>{source.excerpt}</blockquote></section>)}{!evidenceCards(e).length&&<p>此段暂无已登记依据。</p>}<details><summary>技术详情</summary><pre>{JSON.stringify(e,null,2)}</pre></details></article>)}{!evidence.length&&<p>此文稿尚未登记来源绑定。</p>}{selected&&evidence.length>0&&!evidence.some(x=>x.block_id===selected||x.chunk_id===selected)&&<p>当前所选位置没有独立段落依据，可查看全文依据。</p>}</div>}
 {pane==='指标'&&<div className="details">{facts.map(f=><article key={f.id}><strong>{f.label??f.fact_key}</strong> <span>{displayValue(f.value)} {f.unit}</span><small> · {statusLabel(f.verification_status)}</small>{['deterministic_computation','semantica_inference'].includes(f.fact_type)?<small> · 由输入计算或推演</small>:<button disabled={dirty||busy} onClick={()=>change(f.fact_key)}>调整输入</button>}</article>)}</div>}
 {pane==='版本'&&<div className="details">{history.map(v=><article key={v.id}><strong>V{v.version}</strong> {v.change_summary}<details><summary>查看历史正文</summary>{rows(v.content).map((n,i)=><p key={i}>{text(n)}</p>)}</details></article>)}</div>}
 {pane==='导出'&&<div className="details">{['docx','pdf'].map(f=><button key={f} disabled={busy||dirty} onClick={()=>void run(async()=>{await call('writing-export',{...payload(),output_format:f},tab.signal);setExports(rows(await call('writing-exports',payload(),tab.signal)));})}>导出 {f.toUpperCase()}</button>)}<button disabled={busy} onClick={()=>void run(async()=>setExports(rows(await call('writing-exports',payload(),tab.signal))))}>刷新导出状态</button>{exports.map(e=><article key={e.id}>{e.output_format?.toUpperCase()} · {e.status}<span> · 文稿版本 {e.document_version_id}</span>{exportReady(e)&&<button disabled={busy} onClick={()=>void run(()=>props.download(e.id,tab.signal))}>下载</button>}</article>)}</div>}
 </>}<div className={`status ${error?'error':''}`} role="status">{error||(busy?'处理中…':dirty?'有未保存修改':doc?'已保存；受控数值通过指标调整':'选择项目及文稿')}</div>
 {changing&&doc&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="调整输入"><h3>调整权威输入</h3><label>指标<select value={factKey} onChange={e=>setFactKey(e.target.value)}>{facts.filter(f=>!['deterministic_computation','semantica_inference'].includes(f.fact_type)).map(f=><option key={f.id} value={f.fact_key}>{f.label??f.fact_key}</option>)}</select></label><label>新的数值<input type="number" value={value} onChange={e=>setValue(e.target.value)}/></label><label>修改原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{dirty&&<p>请先保存正文，再预览影响。</p>}<footer><button disabled={busy} onClick={()=>setChanging(false)}>取消</button><button disabled={busy||dirty||!value.trim()||!Number.isFinite(Number(value))||!reason.trim()||!factKey} onClick={()=>void previewChange()}>预览影响</button></footer></section></div>}
 {preview&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="事实变化影响预览"><h3>影响预览 · 正文尚未改变</h3><button disabled={busy} onClick={()=>setChosen(proposals.filter(p=>p.selectable).map(p=>p.block_id))}>全选可应用项</button><button disabled={busy} onClick={()=>setChosen([])}>清空选择</button>{proposals.map(p=><article key={p.block_id}><label><input type="checkbox" disabled={busy||!p.selectable} checked={chosen.includes(p.block_id)} onChange={e=>setChosen(s=>e.target.checked?[...s,p.block_id]:s.filter(x=>x!==p.block_id))}/>{p.section??p.block_id}</label><div className="before">{p.old_text??'原内容'}</div><div className="after">{p.new_text??'需人工修订'}</div><small>{p.reason}</small></article>)}{!proposals.length&&<p>尚无可直接采用的正文修改，请检查绑定及计算结果。</p>}<p>未选择处保持原文并标记待更新，不能直接定稿。</p>{error&&<p className="error">{error}</p>}<footer><button disabled={busy} onClick={()=>void cancel()}>取消</button><button disabled={busy||!chosen.length} onClick={()=>void apply()}>应用所选 {chosen.length} 项</button></footer></section></div>}
 </section>;
}
function text(node:Row):string{return typeof node.text==='string'?node.text:rows(node.children).map(text).join('');}
